name: pyanodi

channels:
  - conda-forge
  - defaults

dependencies:
  - python
  - pip
  - numpy
  - scipy
  - numba
  - scikit-image
  - scikit-learn
  - matplotlib
  - pip:
    - git+https://github.com/grongier/pyanodi.git
